apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  ports:
    - name: web
      nodePort: 30001
      protocol: TCP
      targetPort: 8080
      port: 8080
  selector:
    name: jenkins
  type: NodePort